# SPDX-FileCopyrightText: 2024 Ethaks <ethaks@pm.me>
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "Metron"
SPDX-PackageSupplier = "Ethaks <ethaks@pm.me>"
SPDX-PackageDownloadLocation = "https://github.com/Ethaks/FVTT-Metron"
annotations = []
